#!/usr/bin/python3

# function that raises a name exception with message


def raise_exception_msg(message=""):
    raise NameError(message)
